version: "3.8"

services: 
    app:
        build:  .
        command: npm start
        ports: 
            - '3000:3000'
        volumes: 
            - .:/usr/app
        depends_on: 
            - postgres
        networks: 
            - host

    postgres:
        image: postgres
        environment: 
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PW}
            POSTGRES_DB: ${DB_NAME}
        volumes: 
            - ./pgdata:/var/lib/postgresql/data
        ports: 
            - '5432:5432'
        networks: 
            - host
        
networks:  
    host:  